### ISSUE TITLE
Fails on neofetch output

### ISSUE THREAD

**Issue by kj7rrv** [getcuia/stransi#111]
This is my code:

    import subprocess
    import stransi

    neofetch_bytes = subprocess.run(['neofetch'], capture_output=True).stdout
    neofetch_str = neofetch_bytes.decode('utf-8')
    neofetch_ansi = stransi.Ansi(neofetch_str)

    print('neofetch_bytes:')
    print(neofetch_bytes)

    print('----------')

    print('neofetch_str:')
    print(neofetch_str)

    print('----------')

    print('neofetch_ansi:')
    print(neofetch_ansi)

    print('----------')

    print('neofetch_ansi.instructions():')
    print(list(neofetch_ansi.instructions()))

This is the output (to see it as it appears in my terminal, including colors, run `curl https://termbin.com/abyk`):

    neofetch_bytes:
    b'\x1b[?25l\x1b[?7l\x1b[0m\x1b[36m\x1b[1m                   -`\n                  .o+`\n                 `ooo/\n                `+oooo:\n               `+oooooo:\n               -+oooooo+:\n             `/:-:++oooo+:\n            `/++++/+++++++:\n           `/++++++++++++++:\n          `/+++o\x1b[0m\x1b[36m\x1b[1moooooooo\x1b[0m\x1b[36m\x1b[1moooo/`\n\x1b[0m\x1b[36m\x1b[1m         \x1b[0m\x1b[36m\x1b[1m./\x1b[0m\x1b[36m\x1b[1mooosssso++osssssso\x1b[0m\x1b[36m\x1b[1m+`\n\x1b[0m\x1b[36m\x1b[1m        .oossssso-````/ossssss+`\n       -osssssso.      :ssssssso.\n      :osssssss/        osssso+++.\n     /ossssssss/        +ssssooo/-\n   `/ossssso+/:-        -:/+osssso+-\n  `+sso+:-`                 `.-/+oso:\n `++:.                           `-/+/\n .`                                 `/\x1b[0m\n\x1b[19A\x1b[9999999D\x1b[41C\x1b[0m\x1b[1m\x1b[36m\x1b[1mkj7rrv\x1b[0m@\x1b[36m\x1b[1marchlinux\x1b[0m \n\x1b[41C\x1b[0m----------------\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mOS\x1b[0m\x1b[0m:\x1b[0m Arch Linux x86_64\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mHost\x1b[0m\x1b[0m:\x1b[0m Inspiron 3521 A05\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mKernel\x1b[0m\x1b[0m:\x1b[0m 5.18.7-zen1-1-zen\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mUptime\x1b[0m\x1b[0m:\x1b[0m 23 hours, 10 mins\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mPackages\x1b[0m\x1b[0m:\x1b[0m 1412 (pacman)\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mShell\x1b[0m\x1b[0m:\x1b[0m zsh 5.9\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mResolution\x1b[0m\x1b[0m:\x1b[0m 1366x768\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mDE\x1b[0m\x1b[0m:\x1b[0m GNOME 42.3.1\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mWM\x1b[0m\x1b[0m:\x1b[0m Mutter\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mWM Theme\x1b[0m\x1b[0m:\x1b[0m Adwaita\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mTheme\x1b[0m\x1b[0m:\x1b[0m Adwaita [GTK2/3]\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mIcons\x1b[0m\x1b[0m:\x1b[0m breeze [GTK2/3]\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mTerminal\x1b[0m\x1b[0m:\x1b[0m mate-terminal\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mTerminal Font\x1b[0m\x1b[0m:\x1b[0m Monospace 10\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mCPU\x1b[0m\x1b[0m:\x1b[0m Intel Pentium 2117U (2) @ 1.800GHz\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mGPU\x1b[0m\x1b[0m:\x1b[0m Intel 3rd Gen Core processor Graphics Controller\x1b[0m \n\x1b[41C\x1b[0m\x1b[36m\x1b[1mMemory\x1b[0m\x1b[0m:\x1b[0m 2737MiB / 3797MiB\x1b[0m \n\n\x1b[41C\x1b[30m\x1b[40m   \x1b[31m\x1b[41m   \x1b[32m\x1b[42m   \x1b[33m\x1b[43m   \x1b[34m\x1b[44m   \x1b[35m\x1b[45m   \x1b[36m\x1b[46m   \x1b[37m\x1b[47m   \x1b[m\n\x1b[41C\x1b[38;5;8m\x1b[48;5;8m   \x1b[38;5;9m\x1b[48;5;9m   \x1b[38;5;10m\x1b[48;5;10m   \x1b[38;5;11m\x1b[48;5;11m   \x1b[38;5;12m\x1b[48;5;12m   \x1b[38;5;13m\x1b[48;5;13m   \x1b[38;5;14m\x1b[48;5;14m   \x1b[38;5;15m\x1b[48;5;15m   \x1b[m\n\n\n\x1b[?25h\x1b[?7h'
    ----------
    neofetch_str: [in the terminal, this is in color]
                       -`                    kj7rrv@archlinux 
                      .o+`                   ---------------- 
                     `ooo/                   OS: Arch Linux x86_64 
                    `+oooo:                  Host: Inspiron 3521 A05 
                   `+oooooo:                 Kernel: 5.18.7-zen1-1-zen 
                   -+oooooo+:                Uptime: 23 hours, 10 mins 
                 `/:-:++oooo+:               Packages: 1412 (pacman) 
                `/++++/+++++++:              Shell: zsh 5.9 
               `/++++++++++++++:             Resolution: 1366x768 
              `/+++ooooooooooooo/`           DE: GNOME 42.3.1 
             ./ooosssso++osssssso+`          WM: Mutter 
            .oossssso-````/ossssss+`         WM Theme: Adwaita 
           -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3] 
          :osssssss/        osssso+++.       Icons: breeze [GTK2/3] 
         /ossssssss/        +ssssooo/-       Terminal: mate-terminal 
       `/ossssso+/:-        -:/+osssso+-     Terminal Font: Monospace 10 
      `+sso+:-`                 `.-/+oso:    CPU: Intel Pentium 2117U (2) @ 1.800GHz 
     `++:.                           `-/+/   GPU: Intel 3rd Gen Core processor Graphics Controller 
     .`                                 `/   Memory: 2737MiB / 3797MiB 

                                                                     
                                                                     

    ----------
    neofetch_ansi: [in the terminal, this is in color]
                       -`                    kj7rrv@archlinux 
                      .o+`                   ---------------- 
                     `ooo/                   OS: Arch Linux x86_64 
                    `+oooo:                  Host: Inspiron 3521 A05 
                   `+oooooo:                 Kernel: 5.18.7-zen1-1-zen 
                   -+oooooo+:                Uptime: 23 hours, 10 mins 
                 `/:-:++oooo+:               Packages: 1412 (pacman) 
                `/++++/+++++++:              Shell: zsh 5.9 
               `/++++++++++++++:             Resolution: 1366x768 
              `/+++ooooooooooooo/`           DE: GNOME 42.3.1 
             ./ooosssso++osssssso+`          WM: Mutter 
            .oossssso-````/ossssss+`         WM Theme: Adwaita 
           -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3] 
          :osssssss/        osssso+++.       Icons: breeze [GTK2/3] 
         /ossssssss/        +ssssooo/-       Terminal: mate-terminal 
       `/ossssso+/:-        -:/+osssso+-     Terminal Font: Monospace 10 
      `+sso+:-`                 `.-/+oso:    CPU: Intel Pentium 2117U (2) @ 1.800GHz 
     `++:.                           `-/+/   GPU: Intel 3rd Gen Core processor Graphics Controller 
     .`                                 `/   Memory: 2737MiB / 3797MiB 

                                                                     
                                                                     

    ----------
    neofetch_ansi.instructions():
    Traceback (most recent call last):
      File "/home/kj7rrv/projects/neoshare/neoshare.py", line 24, in <module>
        print(list(neofetch_ansi.instructions()))
      File "/home/kj7rrv/.local/lib/python3.10/site-packages/stransi/ansi.py", line 50, in instructions
        yield from escape.instructions()
      File "/home/kj7rrv/.local/lib/python3.10/site-packages/stransi/escape.py", line 58, in instructions
        while token := next(tokens, None):
      File "/home/kj7rrv/.local/lib/python3.10/site-packages/stransi/escape.py", line 42, in tokens
        yield Token(kind=kind, data=int(param))
    ValueError: invalid literal for int() with base 10: '?25l\x1b[?7'

**Comment by kj7rrv** [comment]
If you need the exact byte-for-byte output of `neofetch`, here it is in base64:

    G1s/MjVsG1s/N2wbWzBtG1szNm0bWzFtICAgICAgICAgICAgICAgICAgIC1gCiAgICAgICAgICAg
    ICAgICAgIC5vK2AKICAgICAgICAgICAgICAgICBgb29vLwogICAgICAgICAgICAgICAgYCtvb29v
    OgogICAgICAgICAgICAgICBgK29vb29vbzoKICAgICAgICAgICAgICAgLStvb29vb28rOgogICAg
    ICAgICAgICAgYC86LTorK29vb28rOgogICAgICAgICAgICBgLysrKysvKysrKysrKzoKICAgICAg
    ICAgICBgLysrKysrKysrKysrKysrOgogICAgICAgICAgYC8rKytvG1swbRtbMzZtG1sxbW9vb29v
    b29vG1swbRtbMzZtG1sxbW9vb28vYAobWzBtG1szNm0bWzFtICAgICAgICAgG1swbRtbMzZtG1sx
    bS4vG1swbRtbMzZtG1sxbW9vb3Nzc3NvKytvc3Nzc3NzbxtbMG0bWzM2bRtbMW0rYAobWzBtG1sz
    Nm0bWzFtICAgICAgICAub29zc3Nzc28tYGBgYC9vc3Nzc3NzK2AKICAgICAgIC1vc3Nzc3Nzby4g
    ICAgICA6c3Nzc3Nzc28uCiAgICAgIDpvc3Nzc3Nzcy8gICAgICAgIG9zc3NzbysrKy4KICAgICAv
    b3Nzc3Nzc3NzLyAgICAgICAgK3Nzc3Nvb28vLQogICBgL29zc3Nzc28rLzotICAgICAgICAtOi8r
    b3Nzc3NvKy0KICBgK3Nzbys6LWAgICAgICAgICAgICAgICAgIGAuLS8rb3NvOgogYCsrOi4gICAg
    ICAgICAgICAgICAgICAgICAgICAgICBgLS8rLwogLmAgICAgICAgICAgICAgICAgICAgICAgICAg
    ICAgICAgICBgLxtbMG0KG1sxOUEbWzk5OTk5OTlEG1s0MUMbWzBtG1sxbRtbMzZtG1sxbWtqN3Jy
    dhtbMG1AG1szNm0bWzFtYXJjaGxpbnV4G1swbSAKG1s0MUMbWzBtLS0tLS0tLS0tLS0tLS0tLRtb
    MG0gChtbNDFDG1swbRtbMzZtG1sxbU9TG1swbRtbMG06G1swbSBBcmNoIExpbnV4IHg4Nl82NBtb
    MG0gChtbNDFDG1swbRtbMzZtG1sxbUhvc3QbWzBtG1swbTobWzBtIEluc3Bpcm9uIDM1MjEgQTA1
    G1swbSAKG1s0MUMbWzBtG1szNm0bWzFtS2VybmVsG1swbRtbMG06G1swbSA1LjE4LjctemVuMS0x
    LXplbhtbMG0gChtbNDFDG1swbRtbMzZtG1sxbVVwdGltZRtbMG0bWzBtOhtbMG0gMjMgaG91cnMs
    IDIxIG1pbnMbWzBtIAobWzQxQxtbMG0bWzM2bRtbMW1QYWNrYWdlcxtbMG0bWzBtOhtbMG0gMTQx
    MiAocGFjbWFuKRtbMG0gChtbNDFDG1swbRtbMzZtG1sxbVNoZWxsG1swbRtbMG06G1swbSB6c2gg
    NS45G1swbSAKG1s0MUMbWzBtG1szNm0bWzFtUmVzb2x1dGlvbhtbMG0bWzBtOhtbMG0gMTM2Nng3
    NjgbWzBtIAobWzQxQxtbMG0bWzM2bRtbMW1ERRtbMG0bWzBtOhtbMG0gR05PTUUgNDIuMy4xG1sw
    bSAKG1s0MUMbWzBtG1szNm0bWzFtV00bWzBtG1swbTobWzBtIE11dHRlchtbMG0gChtbNDFDG1sw
    bRtbMzZtG1sxbVdNIFRoZW1lG1swbRtbMG06G1swbSBBZHdhaXRhG1swbSAKG1s0MUMbWzBtG1sz
    Nm0bWzFtVGhlbWUbWzBtG1swbTobWzBtIEFkd2FpdGEgW0dUSzIvM10bWzBtIAobWzQxQxtbMG0b
    WzM2bRtbMW1JY29ucxtbMG0bWzBtOhtbMG0gYnJlZXplIFtHVEsyLzNdG1swbSAKG1s0MUMbWzBt
    G1szNm0bWzFtVGVybWluYWwbWzBtG1swbTobWzBtIG1hdGUtdGVybWluYWwbWzBtIAobWzQxQxtb
    MG0bWzM2bRtbMW1UZXJtaW5hbCBGb250G1swbRtbMG06G1swbSBNb25vc3BhY2UgMTAbWzBtIAob
    WzQxQxtbMG0bWzM2bRtbMW1DUFUbWzBtG1swbTobWzBtIEludGVsIFBlbnRpdW0gMjExN1UgKDIp
    IEAgMS44MDBHSHobWzBtIAobWzQxQxtbMG0bWzM2bRtbMW1HUFUbWzBtG1swbTobWzBtIEludGVs
    IDNyZCBHZW4gQ29yZSBwcm9jZXNzb3IgR3JhcGhpY3MgQ29udHJvbGxlchtbMG0gChtbNDFDG1sw
    bRtbMzZtG1sxbU1lbW9yeRtbMG0bWzBtOhtbMG0gMjkzOU1pQiAvIDM3OTdNaUIbWzBtIAoKG1s0
    MUMbWzMwbRtbNDBtICAgG1szMW0bWzQxbSAgIBtbMzJtG1s0Mm0gICAbWzMzbRtbNDNtICAgG1sz
    NG0bWzQ0bSAgIBtbMzVtG1s0NW0gICAbWzM2bRtbNDZtICAgG1szN20bWzQ3bSAgIBtbbQobWzQx
    QxtbMzg7NTs4bRtbNDg7NTs4bSAgIBtbMzg7NTs5bRtbNDg7NTs5bSAgIBtbMzg7NTsxMG0bWzQ4
    OzU7MTBtICAgG1szODs1OzExbRtbNDg7NTsxMW0gICAbWzM4OzU7MTJtG1s0ODs1OzEybSAgIBtb
    Mzg7NTsxM20bWzQ4OzU7MTNtICAgG1szODs1OzE0bRtbNDg7NTsxNG0gICAbWzM4OzU7MTVtG1s0
    ODs1OzE1bSAgIBtbbQoKChtbPzI1aBtbPzdo

**Comment by kj7rrv** [comment]
The problematic code appears to be `Escape('\x1b[?25l\x1b[?7l')`. It looks like that should be two codes, but it's what I get from `repr(list(neofetch_ansi.escapes())[0])`.

**Comment by kj7rrv** [comment]
Oh, this is caused by #16.
